### ISSUE TITLE
[Epic] Medical cases

### ISSUE THREAD

**Issue by harm-matthias-harms** [harm-matthias-harms/rpm#28]
Good medical cases are a foundation for every working exercise producing good results and learning effects. To handle medical cases in its entirety, different functions need to be provided. This Epic will list all depending user stories. Over time different user stories may be added.

User stories:
- [x] Create medical cases (#29)
- [x] Update medical cases (#30)
- [x] Delete medical cases (#31)
- [x] Print medical case (#33)
- [x] Evolving medical cases (advanced)(#32)
- [ ] Filter medical cases (#63)
- [ ] Comment medical cases (#34)
- [ ] Rate medical cases (#35)
